language: objective-c

branches:
  only:
  - alfa
  - beta
  - stable

addons:
  sonarcloud:
    organization: "rafaelnsantos-github"

os: osx

rvm:
- 2.2

cache:
  directories:
  - ./Unity

before_install:
- chmod a+x ./Travis/install.sh
- chmod a+x ./Travis/build.sh
- chmod a+x ./Travis/tag.sh

install:
- ./Travis/install.sh

script:
- sonar-scanner
- ./Travis/build.sh

after_success:
- ./Travis/tag.sh

deploy:
- provider: releases
  api_key: $GIT_TOKEN
  file: 
  - ./Build/windows.zip
  - ./Build/mac.zip
  - ./Build/linux.zip
  name: $TRAVIS_BRANCH $(date +'%Y.%m.%d %H:%M')
  skip_cleanup: true
  on:
    all_branches: true

- provider: pages
  skip-cleanup: true
  github-token: $GIT_TOKEN
  local-dir: ./Build/webgl/
  keep-history: true
  on:
    branch: stable